db:
  build: docker/database
  environment:
    - RAILS_ENV=development
    - POSTGRES_PASSWORD=vetsgovdev
    - POSTGRES_USER=vetsgovdev
    - POSTGRES_DB=vetsgovdemo-dev
  ports:
    - "6432:5432"
app:
  build: .
  environment:
    - RAILS_ENV=development
  ports:
      - "3000:3000"
  links:
    - db

