default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2
  timeout: 5000
  # Docker Compose adds in the app machine /etc/hosts and entry
  # that points to the container IP where "db" is running
  #@see in docker-compose.yml under "app"
  #     links:
  #       - db
  #
  # It is that IP they put in <link_name>_PORT_5432_TCP_ADDR
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] || 'localhost' %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] || '5432' %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: vetsgovdemo-dev
  username: vetsgovdev
  password: vetsgovdev


test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: vetsgovdemo-test
  username: vetsgovdev
  password: vetsgovdev