# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53b9ae588c9ba61eccdee95f86392decea0d33afec2a2abc82871d89bf35ba821be1f03b435d0794cb89cdde5070c0bf5d022a28f14270daa7239ddd220e006a

test:
  secret_key_base: 2e37b42e48dff54d4a1be95f2ce7518a2c44bfa25ecb1e623a4f6c0720f34ce063e1e4b6101c33978e2d88d4710dc407927fa4adb3d0ca9e4158c960100012d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
